---

role_name: "kubeadm"

# Kubernetes vars
kube_channel: "kubernetes-xenial"
kube_version: "stable-1.9"
kube_token: "c0e6b3.5a3467256293c85b"
kubeadm_config_dir: "/etc/kubeadm"
kubeadm_version: "1.9.1-00"
kubelet_version: "1.9.1-00"
kubectl_config: "/etc/kubernetes/admin.conf"
kube_master_ip: "172.16.0.10"
pod_network_cidr: "10.244.0.0/16"

env_vars: [
  { dest: "/root/.bashrc", line: "export export no_proxy='.{{ domain }},localhost,{% for node in groups['etcd'] %}{{ node }}{% if not loop.last %},{% endif %}{% endfor %}'" }
]

packs: [
  { package: "apt-transport-https" },
  { package: "ca-certificates" },
  { package: "kubelet={{ kubelet_version }}" },
  { package: "kubeadm={{ kubeadm_version }}" }
]

generic_configs: [
  { src: "roles/{{ role_name }}/templates/kubelet.conf.j2", dest: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf",  owner: "root", group: "root", mode: "0644" }
]

master_configs: [
  { src: "roles/{{ role_name }}/templates/config.yml.j2", dest: "{{ kubeadm_config_dir }}/config.yml", owner: "{{ app_user }}", group: "{{ app_user }}", mode: "0644" }
]

dirs: [
  { path: "{{ kubeadm_config_dir }}",     owner: "{{ app_user }}",  group: "{{ app_user }}",  mode: "0644" },
  { path: "/home/{{ app_user }}/.kube/",  owner: "{{ app_user }}",  group: "{{ app_user }}",  mode: "0744" },
  { path: "/root/.kube/",                 owner: "root",            group: "root",            mode: "0744" }
]

copy: [
  { src: "{{ kubectl_config }}", dest: "/home/{{ app_user }}/.kube/config", owner: "{{ app_user }}", group: "{{ app_user }}", mode: "0644"},
  { src: "{{ kubectl_config }}", dest: "/root/.kube/config",                owner: "root",           group: "root",           mode: "0644"},
  { src: "/root/.bashrc",        dest: "/home/{{ app_user }}/.bashrc",      owner: "{{ app_user }}", group: "{{ app_user }}", mode: "0744"}
]
