---

- hosts: cluster
  become: yes
  become_method: sudo
  gather_facts: True

  roles:
    - vagrant # remove this role when installing on different environment
    - users
    - docker
    - kubeadm
    #- helm